/*******************************************************************************
* Copyright (C) 2022 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*******************************************************************************/


/*******************************************************************************
  Application BLE Source File

  Company:
    Microchip Technology Inc.

  File Name:
    app_ble.c

  Summary:
    This file contains the Application BLE implementation for this project.

  Description:
    This file contains the Application BLE implementation for this project.

  Note: 
    The code is automatically generated by MCC based on the GUI settings. The 
    user should not add code to this file to avoid conflicts.
 *******************************************************************************/

#include "app.h"
#include "osal/osal_freertos_extend.h"
#include "app_ble.h"
#include "app_ble_handler.h"
#include "node_config.h"
#include "provisioning.h"





#include "app_trspc_handler.h"
#include "app_trsps_handler.h"









// *****************************************************************************
// *****************************************************************************
// Section: Macros
// *****************************************************************************
// *****************************************************************************


// *****************************************************************************
// *****************************************************************************
// Section: Global Variables
// *****************************************************************************
// *****************************************************************************
BLE_DD_Config_T         g_ddConfig;

// *****************************************************************************
// *****************************************************************************
// Section: Function Prototypes
// *****************************************************************************
// *****************************************************************************


// *****************************************************************************
// *****************************************************************************
// Section: Functions
// *****************************************************************************
// *****************************************************************************

static void APP_BleStackCb(STACK_Event_T *p_stack)
{
    STACK_Event_T stackEvent;
    APP_Msg_T   appMsg;
    APP_Msg_T   *p_appMsg;

    (void)memcpy((uint8_t *)&stackEvent, (uint8_t *)p_stack, sizeof(STACK_Event_T));
    stackEvent.p_event=OSAL_Malloc(p_stack->evtLen);
    if(stackEvent.p_event==NULL)
    {
        return;
    }
    (void)memcpy(stackEvent.p_event, p_stack->p_event, p_stack->evtLen);
    stackEvent.p_event=stackEvent.p_event;

    if (p_stack->groupId==STACK_GRP_GATT)
    {
        GATT_Event_T *p_evtGatt = (GATT_Event_T *)stackEvent.p_event;

        if (p_evtGatt->eventId == GATTS_EVT_CLIENT_CCCDLIST_CHANGE)
        {
            uint8_t *p_payload;

            p_payload = (uint8_t *)OSAL_Malloc((p_evtGatt->eventField.onClientCccdListChange.numOfCccd*4));
            if (p_payload != NULL)
            {
                (void)memcpy(p_payload, (uint8_t *)p_evtGatt->eventField.onClientCccdListChange.p_cccdList, (p_evtGatt->eventField.onClientCccdListChange.numOfCccd*4));
                p_evtGatt->eventField.onClientCccdListChange.p_cccdList = (GATTS_CccdList_T *)p_payload;
            }
        }
    }

    appMsg.msgId=APP_MSG_BLE_STACK_EVT;

    ((STACK_Event_T *)appMsg.msgData)->groupId=p_stack->groupId;
    ((STACK_Event_T *)appMsg.msgData)->evtLen=p_stack->evtLen;
    ((STACK_Event_T *)appMsg.msgData)->p_event=stackEvent.p_event;

    p_appMsg = &appMsg;
    OSAL_QUEUE_Send(&appData.appQueue, p_appMsg, 0);
}

void APP_BleStackEvtHandler(STACK_Event_T *p_stackEvt)
{
    switch(p_stackEvt->groupId)
    {
        case STACK_GRP_BLE_GAP:
        {
            APP_BleGapEvtHandler((BLE_GAP_Event_T *)p_stackEvt->p_event);
        }
        break;

        case STACK_GRP_BLE_L2CAP:
        {
            APP_BleL2capEvtHandler((BLE_L2CAP_Event_T *)p_stackEvt->p_event);
        }
        break;

        case STACK_GRP_BLE_SMP:
        {
            APP_BleSmpEvtHandler((BLE_SMP_Event_T *)p_stackEvt->p_event);
        }
        break;

        case STACK_GRP_GATT:
        {
            APP_GattEvtHandler((GATT_Event_T *)p_stackEvt->p_event);
        }
        break;

        default:
        break;
    }

    //Direct event to BLE middleware
    BLE_DM_BleEventHandler(p_stackEvt);

    BLE_DD_BleEventHandler(&g_ddConfig, p_stackEvt);

    //Direct event to BLE profiles
    /* Transparent Profile Server */
    BLE_TRSPS_BleEventHandler(p_stackEvt);

    /* Transparent Profile Client */
    BLE_TRSPC_BleEventHandler(p_stackEvt);










    OSAL_Free(p_stackEvt->p_event);
}



static void APP_BleConfigBasic(void)
{
    int8_t                          connTxPower;
    int8_t                          advTxPower;
    BLE_GAP_AdvParams_T             advParam;
    uint8_t advData[] = CONFIG_BLE_GAP_ADV_DATA;
    BLE_GAP_AdvDataParams_T         appAdvData;
    uint8_t scanRspData[] = CONFIG_BLE_GAP_SCAN_RSP_DATA;
    BLE_GAP_AdvDataParams_T         appScanRspData;

    uint8_t advNodeId = PROV_GetNodeId();
    if (advNodeId == 0)
    {
        BLE_GAP_Addr_T devAddr;
        BLE_GAP_GetDeviceAddr(&devAddr);
        advNodeId = (devAddr.addr[0] % 99) + 1;
    }
    advData[12] = '0' + (advNodeId / 10);
    advData[13] = '0' + (advNodeId % 10);

    BLE_GAP_SetAdvTxPowerLevel(CONFIG_BLE_GAP_ADV_TX_PWR, &advTxPower);

    (void)memset(&advParam, 0, sizeof(BLE_GAP_AdvParams_T));
    advParam.intervalMin = 160;
    advParam.intervalMax = 320;
    advParam.type = CONFIG_BLE_GAP_ADV_TYPE;
    advParam.advChannelMap = CONFIG_BLE_GAP_ADV_CHANNEL_MAP;
    advParam.filterPolicy = CONFIG_BLE_GAP_ADV_FILT_POLICY;
    BLE_GAP_SetAdvParams(&advParam);

    appAdvData.advLen = CONFIG_BLE_GAP_ADV_DATA_ORIG_LEN;
    (void)memcpy(appAdvData.advData, advData, appAdvData.advLen);
    BLE_GAP_SetAdvData(&appAdvData);

    appScanRspData.advLen = CONFIG_BLE_GAP_SCAN_RSP_DATA_ORIG_LEN;
    (void)memcpy(appScanRspData.advData, scanRspData, appScanRspData.advLen);
    BLE_GAP_SetScanRspData(&appScanRspData);

    BLE_GAP_SetConnTxPowerLevel(CONFIG_BLE_GAP_CONN_TX_PWR, &connTxPower);
}

static void APP_BleConfigAdvance(void)
{
    uint8_t devName[]=CONFIG_BLE_GAP_DEV_NAME_VALUE;

    BLE_SMP_Config_T                smpParam;

    BLE_GAP_ScanningParams_T        scanParam;
    BLE_DM_Config_T                 dmConfig;
    BLE_GAP_ServiceOption_T         gapServiceOptions;

    int8_t                          connTxPower;

    uint8_t nameNodeId = PROV_GetNodeId();
    if (nameNodeId == 0)
    {
        BLE_GAP_Addr_T devAddr2;
        BLE_GAP_GetDeviceAddr(&devAddr2);
        nameNodeId = (devAddr2.addr[0] % 99) + 1;
    }
    devName[7] = '0' + (nameNodeId / 10);
    devName[8] = '0' + (nameNodeId % 10);

    // Configure Device Name
    BLE_GAP_SetDeviceName(sizeof(devName), devName);    /* Device Name */


    // GAP Service option
    gapServiceOptions.charDeviceName.enableWriteProperty = CONFIG_BLE_GAP_SVC_DEV_NAME_WRITE;             /* Enable Device Name Write Property */
    gapServiceOptions.charAppearance.appearance = CONFIG_BLE_GAP_SVC_APPEARANCE;                          /* Appearance */
    gapServiceOptions.charPeriPreferConnParam.enable = CONFIG_BLE_GAP_SVC_PERI_PRE_CP;                    /* Enable Peripheral Preferred Connection Parameters */
    BLE_GAP_ConfigureBuildInService(&gapServiceOptions);

    // Configure scan parameters
    scanParam.type = CONFIG_BLE_GAP_SCAN_TYPE;      /* Scan Type */
    scanParam.interval = CONFIG_BLE_GAP_SCAN_INTERVAL;      /* Scan Interval */
    scanParam.window = CONFIG_BLE_GAP_SCAN_WINDOW;      /* Scan Window */
    scanParam.filterPolicy = CONFIG_BLE_GAP_SCAN_FILT_POLICY;       /* Scan Filter Policy */
    scanParam.disChannel = CONFIG_BLE_GAP_SCAN_DIS_CHANNEL_MAP;      /* Disable specific channel during scanning */
    BLE_GAP_SetScanningParam(&scanParam);

    BLE_GAP_SetConnTxPowerLevel(CONFIG_BLE_GAP_CONN_TX_PWR, &connTxPower);      /* Connection TX Power */

    // Configure SMP parameters
    (void)memset(&smpParam, 0, sizeof(BLE_SMP_Config_T));
    smpParam.ioCapability = CONFIG_BLE_SMP_IOCAP_TYPE;                  /* IO Capability */
    smpParam.authReqFlag = CONFIG_BLE_SMP_OPTION;             /* Authentication Setting */

    BLE_SMP_Config(&smpParam);

    // Configure BLE_DM middleware parameters
    dmConfig.secAutoAccept = CONFIG_BLE_DM_SEC_AUTO_ACCEPT;                          /* Auto Accept Security Request */
    dmConfig.connConfig.autoReplyUpdateRequest = CONFIG_BLE_DM_AUTO_REPLY_UPD_REQ;      /* Auto Accept Connection Parameter Update Request */
    dmConfig.connConfig.minAcceptConnInterval = CONFIG_BLE_DM_MIN_CONN_INTERVAL;    /* Minimum Connection Interval */
    dmConfig.connConfig.maxAcceptConnInterval = CONFIG_BLE_DM_MAX_CONN_INTERVAL;    /* Maximum Connection Interval */
    dmConfig.connConfig.minAcceptPeripheralLatency = CONFIG_BLE_DM_MIN_CONN_LATENCY;    /* Minimum Connection Latency */
    dmConfig.connConfig.maxAcceptPeripheralLatency = CONFIG_BLE_DM_MAX_CONN_LATENCY;    /* Maximum Connection Latency */
    BLE_DM_Config(&dmConfig);


    // Configure BLE_DD middleware parameters
    g_ddConfig.waitForSecurity = CONFIG_BLE_GCM_DD_WAIT_FOR_SEC;
    g_ddConfig.initDiscInCentral = CONFIG_BLE_GCM_DD_INIT_DISC_IN_CNTRL;
    g_ddConfig.initDiscInPeripheral = CONFIG_BLE_GCM_DD_INIT_DISC_IN_PER;
    g_ddConfig.disableConnectedDisc = CONFIG_BLE_GCM_DD_DIS_CONN_DISC;
}

void APP_BleStackInitBasic(void)
{
    BLE_GAP_Init();

    BLE_GAP_AdvInit();              /* Advertising */

    BLE_GAP_ConnPeripheralInit();   /* Peripheral */
}

void APP_BleStackInitAdvance(void)
{
    uint16_t gattsInitParam=GATTS_CONFIG_NONE;

    uint16_t gattcInitParam=GATTC_CONFIG_NONE;

    STACK_EventRegister(APP_BleStackCb);



    BLE_GAP_ScanInit();     /* Scan */

    BLE_GAP_ConnCentralInit();  /* Central */

    /* GAP (BLE_GAP_Init())shall be initialized before SMP */
    BLE_SMP_Init();

    /* GAP/SMP shall be initialized before L2CAP */
    BLE_L2CAP_Init();

    /* GAP/SMP/L2CAP shall be initialized before GATTS */
    GATTS_Init(gattsInitParam);

    /* GATTS shall be initialized before GATTC */
    GATTC_Init(gattcInitParam);     /* Enable Client Role */


    //Initialize BLE middleware
    BLE_DM_Init();
    BLE_DM_EventRegister(APP_DmEvtHandler);

    BLE_DD_Init();
    BLE_DD_EventRegister(APP_DdEvtHandler);



    //Initialize BLE services

    //Initialize BLE profiles
    /* Transparent Profile Server */
    BLE_TRSPS_Init();
    BLE_TRSPS_EventRegister(APP_TrspsEvtHandler);

    /* Transparent Profile Client */
    BLE_TRSPC_Init();
    BLE_TRSPC_EventRegister(APP_TrspcEvtHandler);











    APP_BleConfigAdvance();
}

void APP_BleStackInit(void)
{
    APP_BleStackInitBasic();
    APP_BleConfigBasic();
    APP_BleStackInitAdvance();
}