#!/usr/bin/env python3
"""Generate a comprehensive macros.txt for the BLE terminal.

Produces one-click quick commands for:
  * Quick provisioning -- assign the connected board as Node 1..100
  * Broadcast (ALL nodes) LED at 100% / 50% / 0%
  * Cluster broadcast LED at 100% / 50% / 0% for Cluster 0..9
  * Per-node LED at 100% / 50% / 0% for Node 1..100

Brightness maps to WHITE (R = G = B):  0% -> 0x00, 50% -> 0x32, 100% -> 0x64.
To emit a single color instead, set COLOR to per-channel weights (0..1), e.g.
COLOR = (1, 0, 0) for red -- each channel is scaled by the level.

Run:  python gen_macros.py     # writes macros.txt next to this script
"""

from pathlib import Path

NODES = range(1, 101)        # Node 1..100  (0x01..0x64)
CLUSTERS = range(0, 10)      # Cluster 0..9 (addressed as 0xC0+n)
LEVELS = [("100%", 0x64), ("50%", 0x32), ("0% (off)", 0x00)]
COLOR = (1, 1, 1)            # white; e.g. (1,0,0)=red, (0,1,0)=green


def hexs(*values) -> str:
    return " ".join(f"{v & 0xFF:02X}" for v in values)


def led_frame(dst: int, level: int) -> str:
    r, g, b = (round(level * c) for c in COLOR)
    return hexs(dst, 0x00, 0x00, 0x05, 0x01, r, g, b)


def provision_frame(node_id: int) -> str:
    return hexs(0x00, 0x00, 0x00, 0x05, 0x05, node_id)


def main() -> None:
    lines: list[str] = [
        "# Generated by gen_macros.py -- re-run to regenerate, or edit here directly.",
        "# Format:  Label | HEX BYTES   (a line without '|' is a section header)",
    ]

    def section(title: str) -> None:
        lines.append("")
        lines.append(f"-- {title} --")

    def button(label: str, cmd: str) -> None:
        lines.append(f"{label} | {cmd}")

    section("Quick provisioning (assign connected board)")
    button("Unprovision (erase ID, revert)", hexs(0x00, 0x00, 0x00, 0x05, 0x06))
    for nid in NODES:
        button(f"Provision Node {nid}", provision_frame(nid))

    section("Broadcast -- ALL nodes")
    for name, level in LEVELS:
        button(f"ALL -> {name}", led_frame(0xFF, level))

    section("Cluster broadcast LED")
    for cl in CLUSTERS:
        for name, level in LEVELS:
            button(f"Cluster {cl} -> {name}", led_frame(0xC0 + cl, level))

    for name, level in LEVELS:
        section(f"Node LED {name}")
        for nid in NODES:
            button(f"Node {nid} -> {name}", led_frame(nid, level))

    out = Path(__file__).with_name("macros.txt")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    buttons = sum(1 for ln in lines if "|" in ln and not ln.startswith("#"))
    print(f"wrote {out}  ({buttons} buttons)")


if __name__ == "__main__":
    main()
